version: '3.8'

services:
  teslacamplayer:
    image: dupengcheng66666/teslacamplayer:latest
    container_name: teslacamplayer
    ports:
      - "8188:80"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - UMAMI_SCRIPT_URL=
      - UMAMI_WEBSITE_ID=
    networks:
      - teslacam-network

networks:
  teslacam-network:
    driver: bridge
